name: campus_mobile_experimental
description: Mobile app platform for campus.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.5.3
dependencies:
  barcode_widget: 2.0.4
  connectivity_plus: 6.1.0
  dio: 4.0.6
  encrypt: 5.0.1
  dots_indicator: 3.0.0
  firebase_analytics: 11.3.3
  firebase_core: 3.6.0
  firebase_crashlytics: 4.1.3
  firebase_messaging: 15.1.3
  flutter:
    sdk: flutter
  flutter_dotenv:
    git:
      url: https://github.com/UCSD/flutter_dotenv.git
      ref: master
  flutter_scandit_plugin:
    git:
      url: https://github.com/UCSD/flutter_scandit.git
      ref: scandit-6.6.3
  flutter_linkify: 6.0.0
  flutter_local_notifications: 17.2.3
  flutter_secure_storage: 5.0.2
  flutter_sticky_header: ^0.7.0
  get: 4.6.6
  google_maps_flutter: 2.2.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl: 0.19.0
  liquid_progress_indicator_v2: 0.5.0
  measured_size: 1.0.0
  geolocator: 9.0.2
  package_info_plus: ^8.1.0
  percent_indicator: 4.2.3
  permission_handler: ^11.3.1
  pointycastle: 3.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  uni_links2: 0.6.0+2
  url_launcher: 6.0.20
  webview_flutter: 2.0.13
  wifi_connection:
    git:
      url: https://github.com/UCSD/wifi_connection.git
      ref: 179eb3a322b9d947752b4ff4e810582c3e262e47
  device_info_plus: ^11.1.0
dev_dependencies:
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env